CHTT/CHTT/Areas/Admin/Controllers/AdminKhachHangController.cs
using CHTT.AdditionalFeature;
using Model;
using Model.Framework;
using Model.Library;
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CHTT.Areas.Admin.Controllers
{
    [Authorize]
    public class AdminKhachHangController : Controller
    {
        private CHTTDbContext _context;

        public AdminKhachHangController()
        {
            _context = new CHTTDbContext();
            _context.Configuration.ProxyCreationEnabled = false;
        }
        // GET: Admin/AdminKhachHang
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public JsonResult LoadIndexData() {
            var data = _context.KhachHangs.Select(x => new { x.MaKH, x.HoTen, x.Phai, x.NgaySinh, x.DiaChi, x.SoDienThoai,x.KichHoat }).ToList();
            return Json(new
            {
                data = data,
                status = true
            }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult AOEModal() {
            return View();
        }

        [HttpGet]
        [AllowAnonymous]
        public JsonResult GetNextCustomerID()
        {
            string strCurID = _context.KhachHangs.OrderByDescending(x => x.MaKH).Select(x => new { x.MaKH }).FirstOrDefault().MaKH;
            int intLength = 8;
            int intNextIDNumber = int.Parse(strCurID.Substring(2)) + 1;
            string strNextID = "KH" + intNextIDNumber;
            while (strNextID.Length < intLength)
            {
                strNextID = strNextID.Insert(2, "0");
            }
            return Json(new
            {
                strMaKH = strNextID,
                status = true
            }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult GetEditData(string strMaKH)
        {
            try
            {
                var data = _context.KhachHangs.Find(strMaKH);
                if (data == null)
                {
                    return Json(new
                    {
                        status = false,
                        message = "Lỗi không tìm thấy dữ liệu"
                    }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new
                    {
                        status = true,
                        data = data
                    }
                    , JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception)
            {
                return Json(new
                {
                    status = false,
                    message = "Đã xảy ra lỗi ở phía Server"
                });
            }
        }

        [HttpPost]
        [AllowAnonymous]
        public JsonResult AddOrEdit(KhachHang model, bool isAdd)
        {
            try
            {
                if (isAdd)
                {
                    if (_context.KhachHangs.Where(x => x.TaiKhoan == model.TaiKhoan).Count() == 0)
                    {
                        model.MatKhau = Encryptor.ComputeSHA256Hash(model.MatKhau);
                        _context.KhachHangs.Add(model);
                        _context.SaveChanges();
                        return Json(new
                        {
                            status = true,
                            message = "Đã thêm"
                        });
                    }
                    else
                    {
                        return Json(new
                        {
                            status = false,
                            message = "Tài khoản này đã tồn tại"
                        });
                    }
                }
                else
                {
                    var data = _context.KhachHangs.Find(model.MaKH);
                    data.HoTen = model.HoTen;
                    data.NgaySinh = model.NgaySinh;
                    data.Phai = model.Phai;
                    data.SoDienThoai = model.SoDienThoai;
                    data.DiaChi = model.DiaChi;
                    data.Email = model.Email;
                    if (data.MatKhau != model.MatKhau)
                    {
                        data.MatKhau = Encryptor.ComputeSHA256Hash(model.MatKhau);
                    }
                    data.KichHoat = model.KichHoat;
                    _context.Entry(data).State = System.Data.Entity.EntityState.Modified;
                    _context.SaveChanges();
                    return Json(new
                    {
                        status = true,
                        message = "Đã cập nhật"
                    });
                }
            }
            catch (Exception)
            {
                return Json(new
                {
                    status = false,
                    message = "Đã xảy ra lỗi ở phía Server"
                });
            }
        }

        [HttpPost]
        public JsonResult Delete(string strMaKH)
        {
            try
            {
                var data = _context.KhachHangs.Find(strMaKH);
                if (data == null)
                {
                    return Json(new
                    {
                        status = false,
                        message = "Lỗi không tìm thấy dữ liệu"
                    }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    _context.KhachHangs.Remove(data);
                    _context.SaveChanges();
                    return Json(new
                    {
                        status = true,
                        message = "Đã xóa"
                    }
                    , JsonRequestBehavior.AllowGet);
                }
            }
            catch (DbUpdateException) {
                return Json(new
                {
                    status = false,
                    message = "Không thể xóa khách hàng này do ràng buộc dữ liệu"
                });
            }
            catch (Exception e)
            {
                return Json(new
                {
                    status = false,
                    message = "Đã xảy ra lỗi ở phía Server"
                });
            }
        }
    }
}

CHTT/CHTT/Areas/Admin/Views/AdminKhachHang/CallChinhSuaKhachHang.cshtml
@model Model.KhachHang


<style>


    div#myEditModal .modal-content {
        top: 1.5rem !important;
        margin-bottom: 5.5rem !important;
        width: 40% !important;
        left: 30% !important;
    }

    #myEditModal {
        overflow: auto !important;
    }

    #close-edit-icon {
        float: right;
    }

        #close-edit-icon > :first-child {
            margin-right: .5rem;
        }

    #flex-edit-control {
        display: flex;
        flex-direction: column;
    }

        #flex-edit-control span {
            margin-left: .5rem;
        }

        #flex-edit-control input[type="date"] {
            width: 35%;
            display: inline;
            margin-left: .5rem;
        }

    .modal-body {
        color: black;
        font-size: .9rem;
    }

    .modal-header {
        color: #4e73df;
        height: 3.5rem;
    }

    #radio-edit-control input {
        margin-left: 1rem;
    }

    .modal-title {
        width: 80% !important;
    }

    span#form-edit-valid {
        color: red;
        padding: .3rem !important;
        font-size: .8rem;
        display: none;
        border: 1px solid red;
    }

    span#form-edit-warning {
        color: red;
        padding: .3rem !important;
        font-size: .8rem;
        display: block;
        border: 1px solid red;
    }

    #edit-alert-danger {
        width: auto;
        padding-left: 1rem;
        padding-right: 1rem;
        font-weight: bold;
        text-align: center;
        position: fixed;
        top: 1.5rem;
        right: 2rem;
        display: none;
        z-index: 1000;
    }

    #edit-alert-danger span {
        margin-left: .8rem;
    }
</style>

@*Modal thêm khách hàng*@
<div class="modal" id="myEditModal" role="dialog">
    <div id="edit-alert-danger" class="alert alert-danger">
        <i class="fa fa-times-circle"></i>
        <span>Vui lòng kiểm tra lại thông tin</span>
    </div>
    @*Modal content*@
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">CHỈNH SỬA KHÁCH HÀNG</h4>
            <button class="close" style="cursor: pointer" data-dismiss="modal">&times;</button>
        </div>
        <div class="modal-body">
            @using (Html.BeginForm("ChinhSuaKhachHang", "AdminKhachHang", FormMethod.Post, new { @id = "form-edit" }))
            {
                <input type="hidden" value="@Model.MaKH" name="MaKH"/>
                //
                <div class="form-group">
                    <span id="form-edit-warning" class="alert">Hệ thống sẽ loại bỏ khoảng trắng dư thừa ở đầu và cuối.</span>
                </div>
                //
                <div class="form-group">
                    <label>Họ tên: </label>
                    @Html.TextBoxFor(x => x.HoTen, new { @id = "form-edit-hoten", @class = "form-control" })
                </div>
                //
                <div class="form-group" id="flex-edit-control">
                    <div id="radio-edit-control">
                        <label>Giới tính: </label>
                        @Html.RadioButtonFor(x => x.Phai, "Nam", Model.Phai == "Nam" ?  new { @checked = true } : null )<span>Nam</span>
                        @Html.RadioButtonFor(x => x.Phai, "Nữ", Model.Phai == "Nữ" ? new { @checked = true } : null)<span>Nữ</span>
                    </div>
                    <div>
                        <label>Ngày sinh: </label>
                        <input id="form-edit-date" type="date" name="NgaySinh" class="form-control" value="@Convert.ToDateTime(Model.NgaySinh).ToString("yyyy-MM-dd")" />
                    </div>
                </div>
                //
                <div class="form-group">
                    <label>Địa chỉ:</label>
                    @Html.TextAreaFor(x => x.DiaChi, new { @class = "form-control", @id = "form-edit-diachi" })
                </div>
                //
                <div class="form-group">
                    <label>Số điện thoại:</label>
                    @Html.TextBoxFor(x=>x.SoDienThoai,new { @class = "form-control", @id = "form-edit-sdt" })
                </div>
                //
                <div class="form-group">
                    <label>Email: (không bắt buộc)</label>
                    @Html.TextBoxFor(x => x.Email, new { @class = "form-control", @id = "form-edit-email" })
                </div>
                //
                @*<div class="form-group">
                    <label>Tài khoản:</label>
                    @Html.TextBoxFor(x=>x.TaiKhoan, new { @class = "form-control", @id = "form-edit-tk" })
                </div>*@
                //
                <div class="form-group">
                    <label>Mật khẩu:</label>
                    @Html.PasswordFor(x => x.MatKhau, new { @class = "form-control", @id = "form-edit-mk1", @value = Model.MatKhau })
                </div>
                //
                <div class="form-group">
                    <label>Nhập lại mật khẩu:</label>
                    <input id="form-edit-mk2" type="password" class="form-control" value="@Model.MatKhau" />
                </div>
                <div class="form-group">
                    <span id="form-edit-valid" class="alert">Vui lòng kiểm tra các ô chưa hợp lệ hoặc chưa điền thông tin.</span>
                </div>
                <hr />
                <div id="close-edit-icon">
                    <button class="btn btn-outline-secondary" data-dismiss="modal">Đóng</button>
                    <button id="form-edit-submit" type="submit" class="btn btn-primary">Lưu</button>
                </div>
            }
        </div>
    </div>
</div>

<script>

    $(document).ready(function () {
        $("#myEditModal").fadeIn(500).modal({ backdrop: "static" });
        $('#form-edit-hoten').removeClass('alert-danger');
        $('#form-edit-hoten').addClass('alert-success');
        $('#form-edit-diachi').removeClass('alert-danger');
        $('#form-edit-diachi').addClass('alert-success');
        $('#form-edit-sdt').removeClass('alert-danger');
        $('#form-edit-sdt').addClass('alert-success');
        $('#form-edit-date').removeClass('alert-danger');
        $('#form-edit-date').addClass('alert-success');
        if ($('#form-edit-email').val().trim().length == 0) {
            $('#form-edit-email').removeClass('alert-danger');
            $('#form-edit-email').removeClass('alert-success');
        } else {
            $('#form-edit-email').removeClass('alert-danger');
            $('#form-edit-email').addClass('alert-success');
        }
        $('#form-edit-mk1').removeClass('alert-danger');
        $('#form-edit-mk1').addClass('alert-success');
        $('#form-edit-mk2').removeClass('alert-danger');
        $('#form-edit-mk2').addClass('alert-success');
    });

    $('#form-hoten').focusout(function () {
        $(this).val($(this).val().trim());
        if ($(this).val().trim().length == 0) {
            $(this).removeClass('alert-success');
            $(this).addClass('alert-danger');
        }
        else {
            $(this).removeClass('alert-danger');
            $(this).addClass('alert-success');
        }
    });

    $('#form-edit-diachi').focusout(function () {
        $(this).val($(this).val().trim());
        if ($(this).val().trim().length == 0) {
            $(this).removeClass('alert-success');
            $(this).addClass('alert-danger');
        }
        else {
            $(this).removeClass('alert-danger');
            $(this).addClass('alert-success');
        }
    });

    $('#form-edit-sdt').focusout(function () {
        $(this).val($(this).val().trim());
        if ($(this).val().trim().length == 0 || $.isNumeric($(this).val()) == false) {
            $(this).removeClass('alert-success');
            $(this).addClass('alert-danger');
        }
        else {
            $(this).removeClass('alert-danger');
            $(this).addClass('alert-success');
        }
    });

    $('#form-edit-date').focusout(function () {
        $(this).val($(this).val().trim());
        if ($(this).val().trim().length == 0) {
            $(this).removeClass('alert-success');
            $(this).addClass('alert-danger');
        }
        else {
            $(this).removeClass('alert-danger');
            $(this).addClass('alert-success');
        }
    });

    $('#form-edit-email').focusout(function () {
        $(this).val($(this).val().trim());
        if ($(this).val().trim().length == 0) {
            $(this).removeClass('alert-danger');
            $(this).removeClass('alert-success');
        } else if ($(this).val().indexOf('@Html.Raw("@")') == -1) {
            $(this).removeClass('alert-success');
            $(this).addClass('alert-danger');
            //console.log($(this).val());
        }
        else {
            $(this).removeClass('alert-danger');
            $(this).addClass('alert-success');
        }
    });

    $('#form-edit-mk1').focusout(function () {
        $(this).val($(this).val().trim());
        if ($(this).val().trim().length < 6 || $(this).val().trim().length > 15) {
            $(this).removeClass('alert-success');
            $(this).addClass('alert-danger');
        }
        else {
            $(this).removeClass('alert-danger');
            $(this).addClass('alert-success');
        }
        if ($('#form-edit-mk2').val() != $('#form-mk1').val() || $(this).val().trim().length < 6 || $(this).val().trim().length > 15) {
            $('#form-edit-mk2').removeClass('alert-danger');
            $('#form-edit-mk2').addClass('alert-success');
        }
        else {
                $('#form-edit-mk2').removeClass('alert-success');
                $('#form-edit-mk2').addClass('alert-danger');
        }
    });

    $('#form-edit-mk2').focusout(function () {
        $(this).val($(this).val().trim());
        if ($(this).val() != $('#form-edit-mk1').val() || $(this).val().trim().length < 6 || $(this).val().trim().length > 15) {
            $(this).removeClass('alert-success');
            $(this).addClass('alert-danger');
        }
        else {
            $(this).removeClass('alert-danger');
            $(this).addClass('alert-success');
        }
    });

    $('#form-edit').submit(function (event) {
        if ($('#form-edit-hoten').hasClass('alert-success') && $('#form-edit-diachi').hasClass('alert-success') && $('#form-edit-sdt').hasClass('alert-success') && $('#form-edit-date').hasClass('alert-success') && ($('#form-edit-email').hasClass('alert-success') || $('#form-edit-email').val() == "") && $('#form-edit-mk1').hasClass('alert-success') && $('#form-edit-mk2').hasClass('alert-success')) {
            event.submit();
        }
        event.preventDefault();
        $('#edit-alert-danger').fadeIn(300).delay(2000).hide(300);
        $('#form-edit-valid').css("display", "block");
        //console.log($('#form-edit-hoten').hasClass('alert-success') && $('#form-edit-diachi').hasClass('alert-success') && $('#form-edit-sdt').hasClass('alert-success') && $('#form-edit-date').hasClass('alert-success') && ($('#form-edit-email').hasClass('alert-success') || $('#form-edit-email').val() == "") && $('#form-edit-tk').hasClass('alert-success') && $('#form-edit-mk1').hasClass('alert-success') && $('#form-edit-mk2').hasClass('alert-success'));
    });

</script>

CHTT/CHTT/Areas/Admin/Views/AdminKhachHang/CallThemKhachHang.cshtml
@model Model.KhachHang
<style>


    div#myModal .modal-content {
        top: 1.5rem !important;
        margin-bottom: 5.5rem !important;
        width: 40% !important;
        left: 30% !important;
    }

    #myModal {
        overflow: auto !important;
    }

    .close-icon {
        float: right;
    }

        .close-icon > :first-child {
            margin-right: .5rem;
        }

    #flex-control {
        display: flex;
        flex-direction: column;
    }

        #flex-control span {
            margin-left: .5rem;
        }

        #flex-control input[type="date"] {
            width: 35%;
            display: inline;
            margin-left: .5rem;
        }

    .modal-body {
        color: black;
        font-size: .9rem;
    }

    .modal-header {
        color: #4e73df;
        height: 3.5rem;
    }

    #radio-control input {
        margin-left: 1rem;
    }

    .modal-title {
        width: 80% !important;
    }

    span#form-valid {
        color: red;
        padding: .3rem !important;
        font-size: .8rem;
        display: none;
        border: 1px solid red;
    }

    span#form-warning {
        color: red;
        padding: .3rem !important;
        font-size: .8rem;
        display: block;
        border: 1px solid red;
    }

    #them-alert-danger {
        width: auto;
        padding-left: 1rem;
        padding-right: 1rem;
        font-weight: bold;
        text-align: center;
        position: fixed;
        top: 1.5rem;
        right: 2rem;
        display: none;
        z-index: 1000;
    }

        #them-alert-danger span {
            margin-left: .8rem;
        }
</style>

@*Modal thêm khách hàng*@
<div class="modal" id="myModal" role="dialog">
    <div id="them-alert-danger" class="alert alert-danger">
        <i class="fa fa-times-circle"></i>
        <span>Vui lòng kiểm tra lại thông tin</span>
    </div>
    @*Modal content*@
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">THÊM KHÁCH HÀNG</h4>
            <button class="close" style="cursor: pointer" data-dismiss="modal">&times;</button>
        </div>
        <div class="modal-body">
            @using (Html.BeginForm("ThemKhachHang", "AdminKhachHang", FormMethod.Post, new { @id = "form" }))
            {
                //
                <div class="form-group">
                    <span id="form-warning" class="alert">Hệ thống sẽ loại bỏ khoảng trắng dư thừa ở đầu và cuối.</span>
                </div>
                //
                <div class="form-group">
                    <label>Họ tên: </label>
                    @Html.TextBoxFor(x => x.HoTen, new { @id = "form-hoten", @class = "form-control", @placeholder = "Họ và tên có dấu và không chứa ký tự đặc biệt" })
                </div>
                //
                <div class="form-group" id="flex-control">
                    <div id="radio-control">
                        <label>Giới tính: </label>
                        @Html.RadioButtonFor(x => x.Phai, "Nam", new { @checked = true, @id = "form-phai-nam" })<span>Nam</span>
                        @Html.RadioButtonFor(x => x.Phai, "Nữ", Model.Phai == "Nữ" ? new { @checked = true } : null)<span>Nữ</span>
                    </div>
                    <div>
                        <label>Ngày sinh: </label>
                        <input id="form-date" type="date" name="NgaySinh" class="form-control" value="@{
                            if (Convert.ToDateTime(Model.NgaySinh).ToString("yyyy-MM-dd") != "0001-01-01")
                            {
                                @Convert.ToDateTime(Model.NgaySinh).ToString("yyyy-MM-dd")
                            }
                            else {
                                @DateTime.Today.ToString("yyyy-MM-dd")
                            }
                        }" />
                    </div>
                </div>
                //
                <div class="form-group">
                    <label>Địa chỉ:</label>
                    @Html.TextAreaFor(x => x.DiaChi, new { @class = "form-control", @id = "form-diachi", @placeholder = "VD: Số nhà, tên đường, Phường/Xã, Huyện/Quận, Tỉnh/Thành phố" })
                </div>
                //
                <div class="form-group">
                    <label>Số điện thoại:</label>
                    @Html.TextBoxFor(x => x.SoDienThoai, new { @class = "form-control", @id = "form-sdt", @placeholder = "Chỉ chứa số và KHÔNG có ký tự đặc biệt. VD: 012345678" })
                </div>
                //
                <div class="form-group">
                    <label>Email: (không bắt buộc)</label>
                    @Html.TextBoxFor(x => x.Email, new { @class = "form-control", @id = "form-email", @placeholder = "vidu@email.com hoặc để trống" })
                </div>
                //
                <div class="form-group">
                    <label>Tài khoản:</label>
                    @Html.TextBoxFor(x => x.TaiKhoan, new { @class = "form-control", @id = "form-tk", @placeholder = "Không phân biệt HOA/ THƯỜNG và KHÔNG chứa ký tự đặc biệt" })
                </div>
                //
                <div class="form-group">
                    <label>Mật khẩu:</label>
                    @Html.PasswordFor(x => x.MatKhau, new { @class = "form-control", @id = "form-mk1", @value = Model.MatKhau, @placeholder = "Tối thiểu 6 ký tự, tối đa 15 ký tự, PHÂN BIỆT hoa thường" })
                </div>
                //
                <div class="form-group">
                    <label>Nhập lại mật khẩu:</label>
                    <input id="form-mk2" type="password" class="form-control" value="@Model.MatKhau" placeholder="Xác nhận lại mật khẩu vừa nhập" />
                </div>
                <div class="form-group">
                    <span id="form-valid" class="alert">Vui lòng kiểm tra các ô chưa hợp lệ hoặc chưa điền thông tin.</span>
                </div>
                <hr />
                <div class="close-icon">
                    <button class="btn btn-outline-secondary" data-dismiss="modal">Đóng</button>
                    <button id="form-submit" type="submit" class="btn btn-primary">Lưu</button>
                </div>
            }
        </div>
    </div>
</div>

<script>

    $(document).ready(function () {

            $("#myModal").fadeIn(800).modal({ backdrop: "static" });
    });

    $('#form-hoten').focusout(function () {
        $(this).val($(this).val().trim());
        if ($(this).val().trim().length == 0) {
            $(this).removeClass('alert-success');
            $(this).addClass('alert-danger');
        }
        else {
            $(this).removeClass('alert-danger');
            $(this).addClass('alert-success');
        }
    });

    $('#form-diachi').focusout(function () {
        $(this).val($(this).val().trim());
        if ($(this).val().trim().length == 0) {
            $(this).removeClass('alert-success');
            $(this).addClass('alert-danger');
        }
        else {
            $(this).removeClass('alert-danger');
            $(this).addClass('alert-success');
        }
    });

    $('#form-sdt').focusout(function () {
        $(this).val($(this).val().trim());
        if ($(this).val().trim().length == 0 || $.isNumeric($(this).val()) == false) {
            $(this).removeClass('alert-success');
            $(this).addClass('alert-danger');
        }
        else {
            $(this).removeClass('alert-danger');
            $(this).addClass('alert-success');
        }
    });

    $('#form-date').focusout(function () {
        $(this).val($(this).val().trim());
        if ($(this).val().trim().length == 0) {
            $(this).removeClass('alert-success');
            $(this).addClass('alert-danger');
        }
        else {
            $(this).removeClass('alert-danger');
            $(this).addClass('alert-success');
        }
    });

    $('#form-email').focusout(function () {
        $(this).val($(this).val().trim());
        if ($(this).val().trim().length == 0) {
            $(this).removeClass('alert-danger');
            $(this).removeClass('alert-success');
        }else if ($(this).val().indexOf('@Html.Raw("@")') == -1) {
            $(this).removeClass('alert-success');
            $(this).addClass('alert-danger');
            //console.log($(this).val());
        }
        else {
            $(this).removeClass('alert-danger');
            $(this).addClass('alert-success');
        }
    });

    $('#form-tk').focusout(function () {
        $(this).val($(this).val().trim());
        if ($(this).val().trim().length == 0) {
            $(this).removeClass('alert-success');
            $(this).addClass('alert-danger');
        }
        else {
            $(this).removeClass('alert-danger');
            $(this).addClass('alert-success');
        }
    });

    $('#form-mk1').focusout(function () {
        $(this).val($(this).val().trim());
        if ($(this).val().trim().length < 6 || $(this).val().trim().length > 15) {
            $(this).removeClass('alert-success');
            $(this).addClass('alert-danger');
        }
        else {
            $(this).removeClass('alert-danger');
            $(this).addClass('alert-success');
        }
        if ($('#form-mk2').val() != $('#form-mk1').val() || $(this).val().trim().length < 6 || $(this).val().trim().length > 15) {
            $('#form-mk2').removeClass('alert-success');
            $('#form-mk2').addClass('alert-danger');
        }
        else {
                $('#form-mk2').removeClass('alert-danger');
                $('#form-mk2').addClass('alert-success');
        }
    });

    $('#form-mk2').focusout(function () {
        $(this).val($(this).val().trim());
        if ($(this).val() != $('#form-mk1').val() || $(this).val().trim().length < 6 || $(this).val().trim().length > 15) {
            $(this).removeClass('alert-success');
            $(this).addClass('alert-danger');
        }
        else {
            $(this).removeClass('alert-danger');
            $(this).addClass('alert-success');
        }
    });

    $('#form').submit(function (event) {
        //console.log($('#form-makh').val());
        if ($('#form-hoten').hasClass('alert-success') && $('#form-diachi').hasClass('alert-success') && $('#form-sdt').hasClass('alert-success') && $('#form-date').hasClass('alert-success') && ($('#form-email').hasClass('alert-success') || $('#form-email').val() == "") && $('#form-tk').hasClass('alert-success') && $('#form-mk1').hasClass('alert-success') && $('#form-mk2').hasClass('alert-success')) {
            event.submit();
            @*$.ajax({
                url: "ThemKhachHang",
                type: "POST",
                data: $('#form').serialize(),
            }).done(function () {
                console.log("done");
            }).fail(function () {
                console.log("fail");
            }).always(function () {
                console.log("form submited");
            });
            return;*@
        }
        else {
            $('#them-alert-danger').fadeIn().delay(2000).fadeOut();
            $('#form-valid').css("display", "block");
            console.log("prevent");
            event.preventDefault();
        }
    });

    $('#form').ready(function () {
        //
        //console.log("load form");
        if ($('#form-hoten').val().length != 0) {
                $('#form-hoten').removeClass('alert-danger');
                $('#form-hoten').addClass('alert-success');
                $('#form-diachi').removeClass('alert-danger');
                $('#form-diachi').addClass('alert-success');
                $('#form-sdt').removeClass('alert-danger');
                $('#form-sdt').addClass('alert-success');
                $('#form-date').removeClass('alert-danger');
                $('#form-date').addClass('alert-success');
            if ($('#form-email').val().trim().length == 0) {
                $('#form-email').removeClass('alert-danger');
                $('#form-email').removeClass('alert-success');
            } else {
                $('#form-email').removeClass('alert-danger');
                $('#form-email').addClass('alert-success');
            }
                $('#form-tk').removeClass('alert-success');
                $('#form-tk').addClass('alert-danger');
                $('#form-mk1').removeClass('alert-danger');
                $('#form-mk1').addClass('alert-success');
                $('#form-mk2').removeClass('alert-danger');
                $('#form-mk2').addClass('alert-success');
        }

    });

</script>

CHTT/CHTT/Areas/Admin/Views/AdminKhachHang/ErrorNoti.cshtml
<style>
    #add-alert-danger {
        width: auto;
        padding-left: 1rem;
        padding-right: 1rem;
        font-weight: bold;
        text-align: center;
        position: fixed;
        top: 1.5rem;
        right: 2rem;
        display: block;
        z-index: 2000;
    }

        #add-alert-danger span {
            margin-left: .8rem;
        }
</style>

<div id="add-alert-danger" class="alert alert-danger">
    <i class="fa fa-times-circle"></i>
    <span>@Model</span>
</div>

<script>
    $("#add-alert-danger").delay(2000).fadeOut(500);
</script>

CHTT/CHTT/Areas/Admin/Views/AdminKhachHang/SuccessNoti.cshtml
<style>
    #add-alert-success {
        width: auto;
        padding-left: 1rem;
        padding-right: 1rem;
        font-weight: bold;
        text-align: center;
        position: fixed;
        top: 1.5rem;
        right: 2rem;
        display: block;
        z-index: 2000;
    }

        #add-alert-success span {
            margin-left: .8rem;
        }
</style>

<div id="add-alert-success" class="alert alert-success">
    <i class="fa fa-check-circle"></i>
    <span>@Model</span>
</div>

<script>
    $("#add-alert-success").delay(2000).fadeOut(500);
</script>