CHTT/CHTT/Areas/Admin/Controllers/AdminDonDatController.cs
using CHTT.Areas.Admin.Models;
using Model;
using Model.Library;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CHTT.Areas.Admin.Controllers
{
    [Authorize]
    public class AdminDonDatController : Controller
    {
        private CHTTDbContext _context;

        public AdminDonDatController()
        {
            _context = new CHTTDbContext();
            _context.Configuration.ProxyCreationEnabled = false;
        }
        // GET: Admin/AdminDonDat

        [HttpGet]
        public JsonResult GetMaHD(string strMaDD)
        {
            var data = _context.HoaDons.Where(x => x.MaDD == strMaDD).FirstOrDefault();
            return Json(new { data = data.MaHD,status=true }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public JsonResult LoadIndexData()
        {
            var strSql = "  select dd.MaDD, HoTen as HoTenKH, NgayDat, Sum(SoLuong) as TongSoLuong,TrangThai from DonDat dd join DonDatCT ddct on dd.MaDD = ddct.MaDD join KhachHang kh on kh.MaKH = dd.MaKH group by dd.MaDD, HoTen, NgayDat,TrangThai ";
            var data = _context.Database.SqlQuery<DonDatCTModel>(strSql).ToList();
            return Json(new
            {
                data = data,
                status = true
            }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult AOEModal()
        {
            return View();
        }

        public ActionResult Detail(string strMaDD) {
            if (strMaDD == null)
            {
                return HttpNotFound();
            }
            else {
                ViewBag.MaDD = strMaDD;
                var strMaKH = _context.DonDats.Find(strMaDD).MaKH;
                var data = _context.KhachHangs.Where(x => x.MaKH == strMaKH).FirstOrDefault();
                return View(data);
            }
        }

        [HttpGet]
        public JsonResult LoadTableData(string strMaDD)
        {
            var strSql = "  select ddct.MaSP, (select Link from vw_spanhdaidien where MaSP = ddct.MaSP) as Link,sp.TenSP, ddct.SoLuong, sps.Gia, sps.Size from DonDatCT ddct join SanPham sp on sp.MaSP = ddct.MaSP join SPSize sps on sps.Size = ddct.Size and ddct.MaSP = sps.MaSP where ddct.MaDD = '"+strMaDD+"'";
            var data = _context.Database.SqlQuery<DonDatChiTietModel>(strSql).ToList();
            return Json(new
            {
                data = data,
                status = true
            }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult GetSizeOfProduct(string strMaSP)
        {
            var data = _context.SPSizes.Where(x=>x.MaSP == strMaSP).Select(x=>x.Size).ToList();
            return Json(new
            {
                data = data,
                status = true
            }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult DetailAdditionalData(string strMaDD)
        {
            var data = _context.DonDats.Where(x=>x.MaDD == strMaDD).Select(x=>new { x.NgayDat,x.GhiChu,x.TrangThai}).FirstOrDefault();
            return Json(new
            {
                data = data,
                status = true
            }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult UpdateDetailInformation(DonDatCT model)
        {
            try
            {
                var data = _context.DonDatCTs.Where(x=>x.MaDD == model.MaDD && x.MaSP == model.MaSP && x.Size == model.Size).FirstOrDefault();
                if (data == null)
                {
                    _context.DonDatCTs.Add(model);
                    _context.SaveChanges();
                    return Json(new
                    {
                        status = true,
                        message = "Đã thêm Size mới. Vui lòng xóa Size cũ"
                    });
                }
                else {
                    if (data.SoLuong == model.SoLuong)
                    {
                        return Json(new
                        {
                            status = false,
                            message = "Đã có trong đơn đặt"
                        });
                    }
                    else {
                        _context.DonDatCTs.Remove(data);
                        _context.DonDatCTs.Add(model);
                        _context.SaveChanges();
                        return Json(new
                        {
                            status = true,
                            message = "Đã cập nhật"
                        });
                    }
                }
            }
            catch (Exception)
            {
                return Json(new
                {
                    status = false,
                    message = "Đã xảy ra lỗi ở phía Server"
                });
            }
        }

        [HttpPost]
        public JsonResult DeleteProduct(DonDatCT model)
        {
            try
            {
                var data = _context.DonDatCTs.Where(x => x.MaDD == model.MaDD && x.MaSP == model.MaSP && x.Size == model.Size).FirstOrDefault();
                _context.DonDatCTs.Remove(data);
                _context.SaveChanges();
                return Json(new
                {
                    status = true,
                    message = "Đã cập nhật"
                });
            }
            catch (Exception)
            {
                return Json(new
                {
                    status = false,
                    message = "Đã xảy ra lỗi ở phía Server"
                });
            }
        }

        [HttpPost]
        public JsonResult CancelOrder(string strMaDD)
        {
            try
            {
                var data = _context.DonDats.Find(strMaDD);
                data.TrangThai = 2;
                _context.SaveChanges();
                return Json(new
                {
                    status = true,
                    message = "Đã hủy bỏ đơn hàng"
                });
            }
            catch (Exception)
            {
                return Json(new
                {
                    status = false,
                    message = "Đã xảy ra lỗi ở phía Server"
                });
            }
        }

        [HttpPost]
        public JsonResult ConfirmOrder(DonDat model, List<DonDatChiTietModel> listDetail)
        {
            try
            {
                bool blnCheck = false;
                foreach (var item in listDetail)
                {
                    var product = _context.SPSizes.Where(x=>x.Size == item.Size && x.MaSP == item.MaSP).FirstOrDefault();
                    if (product.SoLuong - item.SoLuong < 0) {
                        blnCheck = true;
                        break;
                    }
                }

                if (blnCheck) {
                    return Json(new
                    {
                        status = false,
                        message = "Số lượng hàng trong kho không đủ. Vui lòng kiểm tra lại"
                    });
                }
                else {
                    var objLastHoaDon = _context.HoaDons.OrderByDescending(x => x.MaHD).FirstOrDefault();
                    var strNextHDID = "";
                    if (objLastHoaDon == null)
                    {
                        strNextHDID = "HD00000001";
                    }
                    else
                    {
                        int intNextHDID = int.Parse(objLastHoaDon.MaHD.Substring(2)) + 1;
                        strNextHDID = "HD" + intNextHDID;
                        while (strNextHDID.Length < 10)
                        {
                            strNextHDID = strNextHDID.Insert(2, "0");
                        }
                    }

                    var strMaNV = "NV001";
                    if (Session["UserID"] != null)
                    {
                        strMaNV = Session["UserID"].ToString();
                    }
                    var dtNgayXuat = DateTime.Now;
                    var newHD = new HoaDon();
                    newHD.MaHD = strNextHDID;
                    newHD.MaKH = model.MaKH;
                    newHD.MaDD = model.MaDD;
                    newHD.MaNV = strMaNV;
                    newHD.NgayXuatHD = dtNgayXuat;
                    newHD.GhiChu = model.GhiChu;
                    _context.HoaDons.Add(newHD);
                    _context.SaveChanges();
                    var etDonDat = _context.DonDats.Find(model.MaDD);
                    etDonDat.TrangThai = 1;
                    foreach (var item in listDetail)
                    {
                        var newCTHD = new HoaDonCT();
                        var product = _context.SPSizes.Where(x=>x.MaSP == item.MaSP && x.Size == item.Size).FirstOrDefault();
                        _context.SPSizes.Remove(product);
                        var replaceProduct = new SPSize()
                        {
                            MaSP = product.MaSP,
                            Gia = product.Gia,
                            Size = product.Size,
                            SoLuong = product.SoLuong - item.SoLuong
                        };
                        _context.SPSizes.Add(replaceProduct);
                        _context.SaveChanges();
                        newCTHD.MaHD = strNextHDID;
                        newCTHD.MaSP = item.MaSP;
                        newCTHD.SoLuong = item.SoLuong;
                        newCTHD.Size = item.Size;
                        newCTHD.Gia = item.Gia;
                        _context.HoaDonCTs.Add(newCTHD);
                    }
                    _context.SaveChanges();
                    return Json(new
                    {
                        status = true,
                        message = "Đã xử lý đơn hàng này"
                    });
                }
            }

CHTT/CHTT/Areas/Admin/Controllers/AdminHomeController.cs
using CHTT.AdditionalFeature;
using Model;
using Model.Library;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CHTT.Areas.Admin.Controllers
{
    [Authorize]
    public class AdminHomeController : Controller
    {
        private CHTTDbContext _context;

        public AdminHomeController()
        {
            _context = new CHTTDbContext();
            _context.Configuration.ProxyCreationEnabled = false;
        }
        // GET: Admin/AdminHome
        public ActionResult Index()
        {
            return View();
        }
        //
        [HttpGet]
        public JsonResult getData()
        {
            var countKH = _context.KhachHangs.Count();
            var countSP = _context.SanPhams.Count();
            var countDD = _context.DonDats.Where(x => x.TrangThai == 0).Count();
            var countPN = _context.PhieuNhaps.Count();
            return Json(new { 
                intKH = countKH,
                intSP = countSP,
                intDD = countDD,
                intPN = countPN,
                status = true
            }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult AccountInformation()
        {
            return View();
        }

        [HttpGet]
        public JsonResult AccountInformationData()
        {
            var userID = Session["UserID"].ToString();
            var userData = _context.NhanViens.Join(_context.ChucVus, x => x.MaChucVu, y => y.MaChucVu, (x, y) => new {
                y.TenChucVu,
                x.MaNV,
                x.HoTen,
                x.Phai,
                x.NgaySinh,
                x.QueQuan,
                x.DiaChi,
                x.SoDienThoai,
                x.Email,
                x.Luong,
            }).Where(x => x.MaNV == userID).FirstOrDefault();
            string userBirthDay = userData.NgaySinh.Day.ToString("00") + '/' + userData.NgaySinh.Month.ToString("00") + '/' + userData.NgaySinh.Year.ToString("00");
            return Json(new { data = userData,userBirthDay = userBirthDay, status = true },JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult UserChangePass(string strCurPass, string strNewPass)
        {
            var userID = Session["UserID"].ToString();
            var userData = _context.NhanViens.Find(userID);
            if(userData.MatKhau == Encryptor.ComputeSHA256Hash(strCurPass))
            {
                userData.MatKhau = Encryptor.ComputeSHA256Hash(strNewPass);
                _context.Entry(userData).State = System.Data.Entity.EntityState.Modified;
                _context.SaveChanges();
                return Json(new { status = true }, JsonRequestBehavior.AllowGet); 
            }
            else
            {
                return Json(new { status = false }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        public JsonResult GetUserPermission()
        {
            try
            {
                var data = Session["UserPermission"].ToString();
                return Json(new { data = data }, JsonRequestBehavior.AllowGet);
            }
            catch (NullReferenceException)
            {
                string datanull = null;
                return Json(new { data = datanull }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

CHTT/CHTT/Areas/Admin/Views/AdminHome/AccountInformation.cshtml
@{
    ViewBag.Title = "AccountInformation";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<link href="~/Areas/Admin/Contents/admin-page-style.css" rel="stylesheet" />
<link href="~/Areas/Admin/Contents/AdminHomeController.css" rel="stylesheet" />
<!-- Page Content -->

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="font-weight-bold text-primary table-title user-infor">Thông tin cá nhân</h6>
        <button class="btn btn-outline-primary btn-md" id="btn-edit-information">
            <span>
                <i class="far fa-edit"></i>
                Đổi mật khẩu
            </span>
        </button>
    </div>
    <div class="card-body">
        <div id="employee-information-container">
            <div id="employee-information-content">
                <table>

                    <tr>
                        <td>Mã nhân viên:</td>
                        <td>Chưa có thông tin</td>
                    </tr>
                    <tr>
                        <td>Họ và tên:</td>
                        <td>Chưa có thông tin</td>
                    </tr>
                    <tr>
                        <td>Giới tính:</td>
                        <td>Chưa có thông tin</td>
                    </tr>
                    <tr>
                        <td>Ngày sinh:</td>
                        <td>Chưa có thông tin</td>
                    </tr>
                    <tr>
                        <td>Chức vụ:</td>
                        <td>Chưa có thông tin</td>
                    </tr>
                    <tr>
                        <td>Mức lương:</td>
                        <td>Chưa có thông tin</td>
                    </tr>
                    <tr>
                        <td>Email:</td>
                        <td>Chưa có thông tin</td>
                    </tr>
                    <tr>
                        <td>Số điện thoại:</td>
                        <td>Chưa có thông tin</td>
                    </tr>
                    <tr>
                        <td>Quê quán:</td>
                        <td>Chưa có thông tin</td>
                    </tr>
                    <tr>
                        <td>Nơi ở hiện nay:</td>
                        <td>Chưa có thông tin</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>
<div id="changepass-modal" class="modal fade" role="dialog" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">ĐỔI MẬT KHẨU</h4>
                <button type="button" class="close" id="close-modal">&times;</button>
            </div>
            <div class="modal-body">
                <form action="/" method="post">
                    <div class="form-group">
                        <label class="label-control">Mật khẩu hiện tại:</label>
                        <input type="password" name="name" id="cur-pass" class="form-control"/>
                    </div>
                    <div class="form-group">
                        <label class="label-control">Mật khẩu mới:</label>
                        <input type="password" name="name" id="new-pass" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label class="label-control">Nhập lại mật khẩu mới:</label>
                        <input type="password" name="name" id="new-pass-again" class="form-control"/>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button class="btn btn-primary" id="save-button">Lưu</button>
            </div>
        </div>
    </div>
</div>

<script src="~/assets/admin/vendor/notify/notify.min.js"></script>
<script src="~/Areas/Admin/Scripts/controllers/admin-page-script.js"></script>
<script src="~/Areas/Admin/Scripts/controllers/UserInformationController.js"></script>

CHTT/CHTT/Areas/Admin/Views/AdminHome/Index.cshtml
@{
    ViewBag.Title = "TRANG CHỦ";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<link href="~/Areas/Admin/Contents/admin-page-style.css" rel="stylesheet" />
<link href="~/Areas/Admin/Contents/AdminHomeController.css" rel="stylesheet" />
<!-- Page Content -->
<div class="row">
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fas fa-tshirt fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right" style="font-weight: bold">
                        <div class="huge" id="sp-name"></div>
                        <div>Sản phẩm</div>
                    </div>
                </div>
            </div>
            <a class="nav-link home-menu" href="@Url.Action("Index","AdminSanPham")">
                <div class="panel-footer">
                    <span class="pull-left">Xem chi tiết</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>

                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-green">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fas fa-user-check fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right" style="font-weight: bold">
                        <div class="huge" id="kh-name"></div>
                        <div>Khách hàng</div>
                    </div>
                </div>
            </div>
            <a class="nav-link home-menu" href="@Url.Action("Index","AdminKhachHang")">
                <div class="panel-footer">
                    <span class="pull-left">Xem chi tiết</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>

                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-yellow">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-shopping-cart fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right" style="font-weight: bold">
                        <div class="huge" id="ddm-name"></div>
                        <div>Đơn đặt mới</div>
                    </div>
                </div>
            </div>
            <a class="nav-link home-menu" href="@Url.Action("Index","AdminDonDat")">
                <div class="panel-footer">
                    <span class="pull-left">Xem chi tiết</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>

                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-red">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fas fa-scroll fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right" style="font-weight: bold">
                        <div class="huge" id="pnh-name"></div>
                        <div>Phiếu nhập hàng</div>
                    </div>
                </div>
            </div>
            <a class="nav-link home-menu" href="@Url.Action("Index","AdminPhieuNhap")">
                <div class="panel-footer">
                    <span class="pull-left">Xem chi tiết</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>

                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
</div>

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="font-weight-bold text-primary table-title">Thông báo</h6>
    </div>
    <div class="card-body" >
        <div id="tb-container">
            <p>Hiện tại không có thông báo nào</p>
        </div>
    </div>
</div>

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="font-weight-bold text-primary table-title">Chương trình khuyến mãi</h6>
    </div>
    <div class="card-body" >
        <div id="km-container">
            <p>Hiện tại không có chương trình khuyến mãi nào</p>
        </div>
    </div>
</div>

<script src="~/assets/admin/vendor/notify/notify.min.js"></script>
<script src="~/Areas/Admin/Scripts/controllers/admin-page-script.js"></script>
<script src="~/Areas/Admin/Scripts/controllers/AdminHomeController.js"></script>