CHTT/CHTT/Areas/Admin/Controllers/AdminSanPhamController.cs
using CHTT.Areas.Admin.Models;
using Model;
using Model.Framework;
using Model.Library;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CHTT.Areas.Admin.Controllers
{
    [Authorize]
    public class AdminSanPhamController : Controller
    {
        private CHTTDbContext _context;

        public AdminSanPhamController() {
            _context = new CHTTDbContext();
            _context.Configuration.ProxyCreationEnabled = false;
        }
        // GET: Admin/AdminSanPham
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public JsonResult LoadIndexData() {
            /*try
            {
                string strQuery = "select distinct sp.MaSP, TenNCC,TenSP, Link, (select sum(SoLuong) from SPSize where MaSP = sp.MaSP) as SoLuong from SanPham sp left join (select top(1) * from SPHinhAnh order by Link asc) spha on spha.MaSP = sp.MaSP join NhaCC ncc on ncc.MaNCC = sp.MaNCC left join SPSize spz on spz.MaSP = sp.MaSP join SPDoiTuongData spdt on spdt.MaDoiTuong = sp.MaDoiTuong";
                var model = _context.Database.SqlQuery<AdminSanPhamIndexModel>(strQuery).ToList();
                return Json(new
                {
                    data = model,
                    status = true
                }, JsonRequestBehavior.AllowGet);
            } catch (Exception) {
                return Json(new { 
                    status = false,
                    message="Đã xảy ra lỗi khi tải danh sách sản phẩm"
                }, JsonRequestBehavior.AllowGet);
            }*/
            string strQuery = "select distinct sp.MaSP, TenNCC,TenSP, Link, (select sum(SoLuong) from SPSize where MaSP = sp.MaSP) as SoLuong, TenDoiTuong "+
                "from SanPham sp left join (select * from vw_spanhdaidien) spha on spha.MaSP = sp.MaSP join NhaCC ncc on ncc.MaNCC = sp.MaNCC" +
                " left join SPSize spz on spz.MaSP = sp.MaSP left join SPDoiTuongData spdt on spdt.MaDoiTuong = sp.MaDoiTuong";
            var model = _context.Database.SqlQuery<AdminSanPhamIndexModel>(strQuery).ToList();
            return Json(new
            {
                data = model,
                status = true
            }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult AddOrEdit(string strID) {
            if (strID == null)
            {
                string lastMaSP;
                if (_context.SanPhams.Count() > 0)
                {
                    lastMaSP = _context.SanPhams.OrderByDescending(x => x.MaSP).FirstOrDefault().MaSP;
                }
                else
                {
                    lastMaSP = "0";
                }
                int nextID = int.Parse(lastMaSP.Substring(2)) + 1;
                string nextMaSP = "SP" + nextID;
                while (nextMaSP.Length < 8)
                {
                    nextMaSP = nextMaSP.Insert(2, "0");
                }
                ViewBag.addState = true;
                ViewBag.MSSP = nextMaSP;
                return View();
            }
            else
            {
                ViewBag.addState = false;
                ViewBag.MSSP = strID;
                return View();
            }
        }

        [HttpGet]
        public ActionResult Information(string strID) {
            ViewBag.DoiTuong = _context.SPDoiTuongDatas.ToList();
            ViewBag.Loai = _context.SPLoaiDatas.ToList();
            ViewBag.CTLoai = _context.SPCTLoaiDatas.ToList();
            /*ViewBag.TenNCC = _context.NhaCCs.Select(x => new { x.MaNCC, x.TenNCC }).ToList();*/
            if (_context.SanPhams.Count(x => x.MaSP == strID) > 0)
            {
                return View(new AdminSanPham().getInformation(strID));
            }
            else
            {
                return View();
            }
        }

        [HttpPost]
        public JsonResult AddOrEditInformation(AdminSanPhamInformationModel model) {
            try {
                if (_context.SanPhams.Count(x => x.MaSP == model.MaSP) == 0)
                {
                    var spPhanLoai = new SPPhanLoai();
                    spPhanLoai.MaSP = model.MaSP;
                    spPhanLoai.MaLoai = model.MaLoai;
                    spPhanLoai.MaCTLoai = model.MaCTLoai;
                    var sp = new SanPham();
                    sp.MaSP = model.MaSP;
                    sp.MaNCC = model.MaNCC;
                    sp.TenSP = model.TenSP;
                    sp.MaDoiTuong = model.MaDoiTuong;
                    sp.MoTa = model.MoTa;
                    _context.SanPhams.Add(sp);
                    _context.SPPhanLoais.Add(spPhanLoai);
                    _context.SaveChanges();
                    return Json(new
                    {
                        status = true,
                        message = "Đã lưu thông tin sản phẩm mới"
                    });
                }
                else
                {
                    var spPhanLoai = _context.SPPhanLoais.Where(x => x.MaSP == model.MaSP).SingleOrDefault();
                    var sp = _context.SanPhams.Find(model.MaSP);
                    if (spPhanLoai != null)
                    {
                        _context.SPPhanLoais.Remove(spPhanLoai);
                    }
                    spPhanLoai = new SPPhanLoai();
                    spPhanLoai.MaSP = model.MaSP;
                    spPhanLoai.MaLoai = model.MaLoai;
                    spPhanLoai.MaCTLoai = model.MaCTLoai;
                    _context.SPPhanLoais.Add(spPhanLoai);
                    sp.TenSP = model.TenSP;
                    sp.MaDoiTuong = model.MaDoiTuong;
                    sp.MoTa = model.MoTa;
                    _context.SaveChanges();
                    return Json(new
                    {
                        status = true,
                        message = "Đã lưu cập nhật"
                    });
                }
            }
            catch (Exception)
            {
                return Json(new
                {
                    status = false,
                    message = "Đã xảy ra lỗi khi lưu"
                });
            }
        }

        [HttpGet]
        public JsonResult Size(string strID) {
            try
            {
                var model = _context.SPSizes.Where(x => x.MaSP == strID).ToList();
                return Json(new
                {
                    data = model,
                    status = true
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception) {
                return Json(new
                {
                    status = true,
                    message="Đã xảy ra lỗi khi tải danh sách size"
                }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        public ActionResult ModalSize() {
            return View(new SPSize());
        }

        [HttpPost]
        public JsonResult AddOrEditSize(SPSize model, bool state) {
            string message = "";
            bool status = false;
            try
            {
                var data = _context.SPSizes.Where(x => x.MaSP == model.MaSP && x.Size == model.Size).SingleOrDefault();
                if (data != null && state == true)
                {
                    status = false;
                    message = "Size đã tồn tại";
                }
                else if (data != null && state == false)
                {
                    _context.SPSizes.Remove(data);
                    _context.SPSizes.Add(model);
                    _context.SaveChanges();
                    status = true;
                    message = "Đã lưu cập nhật";
                }
                else
                {
                    _context.SPSizes.Add(model);
                    _context.SaveChanges();
                    status = true;
                    message = "Đã lưu size mới";
                }
                return Json(new
                {
                    status = status,
                    message = message

                });
            }
            catch (Exception) {
                return Json(new
                {
                    status = status,
                    message = "Đã xảy ra lỗi khi lưu"

                });
            }
        }

        [HttpPost]
        public ActionResult DeleteSizeRecord(string strMaSP, string strSize) {
            string message = "";
            bool status = false;
            try
            {
                var model = _context.SPSizes.Where(x => x.MaSP == strMaSP && x.Size == strSize).FirstOrDefault();
                _context.SPSizes.Remove(model);
                _context.SaveChanges();
                status = true;
                message = "Đã xóa";
                return Json(new
                {
                    status = status,
                    message = message
                });
            }
            catch (Exception) {
                return Json(new
                {
                    status= status,
                    message = "Đã xảy ra lỗi khi xóa"
                });
            }
        }

        [HttpGet]
        public JsonResult GetSizeEditData(string strMaSP, string strSize) {
            bool status = false;
            try
            {
                var model = _context.SPSizes.Where(x => x.MaSP == strMaSP && x.Size == strSize).FirstOrDefault();
                status = true;
                return Json(new
                {
                    status = status,
                    data = model
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception) {
                return Json(new
                {
                    status = status,
                    message="Đã xảy ra lỗi tải dữ liệu"
                }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]

CHTT/CHTT/Areas/Admin/Controllers/TestController.cs
using CHTT.Areas.Admin.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using Test.Table;

namespace CHTT.Areas.Admin.Controllers
{
    public class TestController : Controller
    {
        private EmployeeDbContext _context;
        public TestController() {
            _context = new EmployeeDbContext();
        }

        public ActionResult Index() {
            return View();
        }

        [HttpGet]
        public JsonResult loadData(int page, int pageSize) {
            var model = _context.Employees.OrderBy(x=>x.ID).Skip((page - 1) * pageSize).Take(pageSize);
            var totalRow = _context.Employees.Count();
            return Json(new { 
                data = model,
                total = totalRow,
                status = true
            }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult updateSalary(string model) {
            JavaScriptSerializer serializer = new JavaScriptSerializer();
            Employee deTestMember = serializer.Deserialize<Employee>(model);
            var testMember = _context.Employees.Single(x=>x.ID == deTestMember.ID);
            testMember.Salary = deTestMember.Salary;
            var checkSave = _context.Employees.Single(x => x.ID == deTestMember.ID);
            return Json(new { status = true });
        }

        [HttpPost]
        public JsonResult addUpdateEmployee(string strData, int id)
        {
            JavaScriptSerializer serializer = new JavaScriptSerializer();
            Employee deTestMember = serializer.Deserialize<Employee>(strData);
            if (id == 1)
            {
                try
                {
                    _context.Employees.Add(deTestMember);
                    _context.SaveChanges();
                    return Json(new { status = true });
                }
                catch (Exception e)
                {
                    return Json(new { status = false });
                }
            }
            else
            {
                Employee model = _context.Employees.Find(deTestMember.ID);
                try
                {
                    model.Name = deTestMember.Name;
                    model.Salary = deTestMember.Salary;
                    model.Status = deTestMember.Status;
                    _context.SaveChanges();
                    return Json(new { status = true });
                }
                catch (Exception e)
                {
                    return Json(new { status = false });
                }
            }
        }

        [HttpGet]
        public JsonResult getDetail(int id)
        {
            var model = _context.Employees.Find(id);
            return Json(new
            {
                data = model,
                status = true
            }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult deleteEmployee(int id)
        {
            try
            {
                var model = _context.Employees.Find(id);
                _context.Employees.Remove(model);
                _context.SaveChanges();
            }
            catch (Exception e) {
                return Json(new { status = false });
            }
            return Json(new { status = true });
        }

        [HttpGet]
        public JsonResult loadDataToDT() {
            var data = _context.Employees.ToList();
            return Json(new { 
                data = data
            }, JsonRequestBehavior.AllowGet);
        }
    }


    // GET: Admin/Test
    /*public ActionResult Index()
    {
        var list = new List<TestModel>();
        list.Add(new TestModel("Yame", "NCC01"));
        list.Add(new TestModel("Toto", "NCC02"));
        list.Add(new TestModel("4Men", "NCC03"));
        list.Add(new TestModel("Chuot xam", "NCC04"));
        ViewBag.list = new SelectList(list, "Value", "Name");
        return View();
    }

    [HttpPost]
    public ActionResult Index(string Value) {
        return Content(Value);
    }

    public ActionResult Create() {
        var list = new List<TestModel>();
        list.Add(new TestModel("Yame", "NCC01"));
        list.Add(new TestModel("Toto", "NCC02"));
        list.Add(new TestModel("4Men", "NCC03"));
        list.Add(new TestModel("Chuot xam", "NCC04"));
        ViewBag.Name3 = new SelectList(list, "Value", "Name",null);

        ViewBag.Value = new SelectList(list, "Name", "Value", "NCC01");

        ViewBag.Name2 = new SelectList(list, "Value", "Name", null);
        return View();
    }*/

    /*List<TestModel> listTestModel = new List<TestModel>() {
            new TestModel()
            {
                ID = 1,
                Name = "Nguyen Van A",
                Salary = 5000000,
                Status = true
            },
            new TestModel()
            {
            ID = 2,
                Name = "Nguyen Van B",
                Salary = 10000000,
                Status = true
            },
            new TestModel()
            {
            ID = 3,
                Name = "Nguyen Van C",
                Salary = 15000000,
                Status = true
            },
            new TestModel()
            {
            ID = 4,
                Name = "Nguyen Van D",
                Salary = 20000000,
                Status = true
            },
            new TestModel()
            {
            ID = 5,
                Name = "Nguyen Van E",
                Salary = 25000000,
                Status = true
            },
            new TestModel()
            {
            ID = 6,
                Name = "Nguyen Van E",
                Salary = 25000000,
                Status = true
            },
            new TestModel()
            {
            ID = 7,
                Name = "Nguyen Van E",
                Salary = 25000000,
                Status = true
            },
            new TestModel()
            {
            ID = 8,
                Name = "Nguyen Van E",
                Salary = 25000000,
                Status = true
            },
            new TestModel()
            {
            ID = 9,
                Name = "Nguyen Van E",
                Salary = 25000000,
                Status = true
            },
            new TestModel()
            {
            ID = 10,
                Name = "Nguyen Van E",
                Salary = 25000000,
                Status = true
            },
            new TestModel()
            {
            ID = 11,
                Name = "Nguyen Van E",
                Salary = 25000000,
                Status = true
            },
            new TestModel()
            {
            ID = 12,
                Name = "Nguyen Van E",
                Salary = 25000000,
                Status = true
            },
            new TestModel()
            {
            ID = 13,
                Name = "Nguyen Van E",
                Salary = 25000000,
                Status = true
            },
            new TestModel()
            {
            ID = 14,
                Name = "Nguyen Van E",
                Salary = 25000000,
                Status = true
            }
        };*/
}

CHTT/CHTT/Areas/Admin/Views/AdminSanPham/AddOrEdit.cshtml
@{
    ViewBag.Title = "AddOrEdit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<link href="~/Areas/Admin/Contents/admin-page-style.css" rel="stylesheet" />
<link href="~/Areas/Admin/Contents/AdminSanPhamController.css" rel="stylesheet" />
<link href="~/assets/admin/vendor/datatables/dataTables.bootstrap4.css" rel="stylesheet" />
<div id="top-page-alert" class="alert alert-warning">
    <span>Bạn có thể thêm mới sản phẩm khác bằng cách reload lại trang. Đừng quên <b>Lưu</b> sản phẩm hiện tại nhé</span>
</div>
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="font-weight-bold text-primary table-title-custom">Thông tin chi tiết</h6>
        <button class="btn btn-primary btn-md" id="btn-save-information" >
            <span>
                Lưu
            </span>
        </button>
        <button class="btn btn-dark btn-md" id="btn-cancel-information" >
            <span>
                Hủy bỏ
            </span>
        </button>
        <button class="btn btn-outline-primary btn-md" id="btn-edit-information" >
            <span>
                <i class="far fa-edit"></i>
                Chỉnh sửa
            </span>
        </button>
    </div>
    <div class="card-body">
        <div id="MSSP" data-id="@ViewBag.MSSP" style="display:none"></div>
        <div id="information-container"></div>
    </div>
</div>

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="font-weight-bold text-primary table-title-custom">Phân loại và giá bán</h6>
        <button class="btn btn-outline-primary btn-md" id="btn-add-size" >
            <span>
                <i class="fa fa-plus" aria-hidden="true"></i>
                Thêm
            </span>
        </button>
    </div>
    <div class="card-body">
        <div id="size-container" class="table-responsive">
            <table id="size-table" class="table table-bordered table-striped" width="100%">
                <thead>
                    <tr>
                        <td>Size</td>
                        <td>Giá bán</td>
                        <td>Số lượng</td>
                        <td>Hành động</td>
                    </tr>
                </thead>
            </table>
        </div>
        <div id="aoe-size-modal">

        </div>
    </div>
</div>

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="font-weight-bold text-primary table-title-custom">Hình ảnh sản phẩm</h6>
        <button class="btn btn-primary btn-md" id="btn-save-images" >
            <span>
                Lưu
            </span>
        </button>
        <button class="btn btn-dark btn-md" id="btn-cancel-images" >
            <span>
                Hủy bỏ
            </span>
        </button>
        <label for="file" class="btn btn-outline-primary btn-md" id="btn-add-images" >
            <span>
                <i class="fa fa-plus" aria-hidden="true"></i>
                Thêm
            </span>
        </label>
        <form id="add-new-image-form" enctype="multipart/form-data">
            <input type="file" id="file" name="file" accept=".png,.jpg,.jpge" multiple />
        </form>
    </div>
    <div class="card-body">
        <div id="image-container">
            <span class="image-length"></span>
            <div id="image-list"></div>
        </div>
    </div>
</div>
<script src="~/assets/admin/vendor/datatables/jquery.dataTables.min.js"></script>
<script src="~/assets/admin/vendor/datatables/dataTables.bootstrap4.min.js"></script>
<script src="~/assets/admin/vendor/notify/notify.min.js"></script>
<script>
    var AOEProductState = @Html.Raw(Json.Encode(ViewBag.addState));
</script>
<script src="~/Areas/Admin/Scripts/controllers/AdminSanPhamAddOrEdit.js"></script>

CHTT/CHTT/Areas/Admin/Views/AdminSanPham/ChiTiet.cshtml
@model Model.SanPham

<div id="form-thong-tin">
    @using (Html.BeginForm())
    {
        <div class="form-group">
            @Html.DisplayNameFor(x => x.MaSP)
            <br />
            @Html.TextBoxFor(x => x.MaSP, new { @class="form-control"})
        </div>

        <div class="form-group">
            @Html.DisplayNameFor(x => x.TenSP)
            @Html.TextBoxFor(x => x.TenSP, new { @class = "form-control" })
        </div>

        <div class="form-group">
            @Html.DisplayNameFor(x => x.GioiTinh)
            @Html.TextBoxFor(x => x.GioiTinh, new { @class = "form-control" })
        </div>

        <div class="form-group">
            @Html.DisplayNameFor(x => x.MaNCC)
            @Html.TextBoxFor(x => x.MaNCC, new { @class = "form-control" })
        </div>

        <div class="form-group">
            @Html.DisplayNameFor(x => x.LoaiSP)
            @Html.TextBoxFor(x => x.LoaiSP, new { @class = "form-control" })
        </div>

        <div class="form-group">
            @Html.DisplayNameFor(x => x.ChungLoai)
            @Html.TextBoxFor(x => x.ChungLoai, new { @class = "form-control" })
        </div>

        <div class="form-group">
            @Html.DisplayNameFor(x => x.MoTa)
            @Html.TextAreaFor(x => x.MoTa, new { @class = "form-control", @style="min-height: 150px"})
        </div>
        
    }
</div>

CHTT/CHTT/Areas/Admin/Views/AdminSanPham/ChiTietSanPham.cshtml
@{
    ViewBag.Title = "CHI TIẾT SẢN PHẨM";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";

}

<style>
    #sp-content {
        display: flex;
        justify-content: space-evenly;
    }

    #hinh-anh{
        display: flex;
        flex-wrap: wrap;
        flex-grow: 0;
        flex-shrink: 0;
        justify-content: space-evenly;
    }

    img{
        width: 39%;
        height: 28%;
        margin: 1.5rem 0;
        box-shadow: 1px 1px 5px #4e73df;
    }

    #sp-pl-container{
        flex: 0 0 50%;
    }

    #hinh-anh-container {
        flex: 0 0 45%;
        overflow-y: visible;
    }

    #form-thong-tin{
        margin: .5rem 1.3rem;
    }

    .span-title {
        width: 92%;
        float: left;
        margin-top: .5rem !important;
    }

    .btn-title{
        float:right;
    }
</style>

<div id="sp-content">
    <div id="sp-pl-container">
        <div id="chi-tiet-container" class="card shadow mb-4">
            <div class="card-header py-3">
                <span class="m-0 text-primary font-weight-bold span-title">Thông tin sản phẩm</span>
                @*<div class="btn btn-outline-warning btn-md btn-title">
                    <span>
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16" style="margin-top: -.2rem">
                            <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456l-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
                            <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z" />
                        </svg>
                        Chỉnh sửa
                    </span>
                </div>*@
            </div>
            <div id="chi-tiet">

            </div>
        </div>
        <div id="phan-loai-container" class="card shadow mb-4">
            <div class="card-header py-3">
                <span class="m-0 text-primary font-weight-bold span-title ">Phân loại theo kích thước</span>
                <div class="btn btn-outline-primary btn-md btn-title ">
                    <span>
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-folder-plus" viewBox="0 0 16 16" style="margin-top: -.2rem">
                            <path d="M.5 3l.04.87a1.99 1.99 0 0 0-.342 1.311l.637 7A2 2 0 0 0 2.826 14H9v-1H2.826a1 1 0 0 1-.995-.91l-.637-7A1 1 0 0 1 2.19 4h11.62a1 1 0 0 1 .996 1.09L14.54 8h1.005l.256-2.819A2 2 0 0 0 13.81 3H9.828a2 2 0 0 1-1.414-.586l-.828-.828A2 2 0 0 0 6.172 1H2.5a2 2 0 0 0-2 2zm5.672-1a1 1 0 0 1 .707.293L7.586 3H2.19c-.24 0-.47.042-.684.12L1.5 2.98a1 1 0 0 1 1-.98h3.672z" />
                            <path d="M13.5 10a.5.5 0 0 1 .5.5V12h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V13h-1.5a.5.5 0 0 1 0-1H13v-1.5a.5.5 0 0 1 .5-.5z" />
                        </svg>
                        Thêm kích thước
                    </span>
                </div>
            </div>
            <div id="phan-loai">

            </div>
        </div>
    </div>


    <div id="hinh-anh-container" class="card shadow mb-4">
        <div class="card-header py-3">
            <span class="m-0 text-primary font-weight-bold span-title">Hình ảnh</span>
            <div class="btn btn-outline-primary btn-md btn-title">
                <span>
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-folder-plus" viewBox="0 0 16 16" style="margin-top: -.2rem">
                        <path d="M.5 3l.04.87a1.99 1.99 0 0 0-.342 1.311l.637 7A2 2 0 0 0 2.826 14H9v-1H2.826a1 1 0 0 1-.995-.91l-.637-7A1 1 0 0 1 2.19 4h11.62a1 1 0 0 1 .996 1.09L14.54 8h1.005l.256-2.819A2 2 0 0 0 13.81 3H9.828a2 2 0 0 1-1.414-.586l-.828-.828A2 2 0 0 0 6.172 1H2.5a2 2 0 0 0-2 2zm5.672-1a1 1 0 0 1 .707.293L7.586 3H2.19c-.24 0-.47.042-.684.12L1.5 2.98a1 1 0 0 1 1-.98h3.672z" />
                        <path d="M13.5 10a.5.5 0 0 1 .5.5V12h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V13h-1.5a.5.5 0 0 1 0-1H13v-1.5a.5.5 0 0 1 .5-.5z" />
                    </svg>
                    Thêm hình ảnh
                </span>
            </div>
        </div>
        <div id="hinh-anh">

        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        ctUrl = '@Html.Raw(Url.Action("ChiTiet","AdminSanPham"))';
        haUrl = '@Html.Raw(Url.Action("HinhAnh","AdminSanPham"))';
        plUrl = '@Html.Raw(Url.Action("PhanLoai","AdminSanPham"))';
        ctUrl += '?id=@Model';
        haUrl += '?id=@Model';
        plUrl += '?id=@Model';
        $('#chi-tiet').load(ctUrl);
        $('#hinh-anh').load(haUrl);
        $('#phan-loai').load(plUrl);
    });
</script>

CHTT/CHTT/Areas/Admin/Views/AdminSanPham/ErrorNoti.cshtml
<style>
    #add-alert-danger {
        width: auto;
        padding-left: 1rem;
        padding-right: 1rem;
        font-weight: bold;
        text-align: center;
        position: fixed;
        top: 1.5rem;
        right: 2rem;
        display: block;
        z-index: 2000;
    }

        #add-alert-danger span {
            margin-left: .8rem;
        }
</style>

<div id="add-alert-danger" class="alert alert-danger">
    <i class="fa fa-times-circle"></i>
    <span>@Model</span>
</div>

<script>
    $("#add-alert-danger").delay(2000).fadeOut(500);
</script>

CHTT/CHTT/Areas/Admin/Views/AdminSanPham/HinhAnh.cshtml
@model List<Model.SPHinhAnh>
<style>
    #them-hinh-anh{
        width: 100%;
    }
</style>
<div id="them-hinh-anh">
    @using (Html.BeginForm())
    {

        <div class="form-group">
            <label>Upload hình:</label>
            <label for="upload-hinh-anh">Chọn hình</label>
            <input type="file" multiple name="Link" id="upload-hinh-anh"/>
        </div>
    }
</div>

@foreach (var ha in Model)
{
    <img src="@ha.Link" alt="Alternate Text" />
}

CHTT/CHTT/Areas/Admin/Views/AdminSanPham/TestView.cshtml
@{
    ViewBag.Title = "TestView";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<button id="test-btn" onclick="change()">click me!</button>

<script>
    function change() {
        window.location.href = "Index";
        alert(window.location.href);
    }
</script>