CHTT/CHTT/Areas/Admin/Controllers/AdminNhaCungCapController.cs
using Model;
using Model.Library;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace CHTT.Areas.Admin.Controllers
{
    [Authorize]
    public class AdminNhaCungCapController : Controller
    {
        private CHTTDbContext _context;

        public AdminNhaCungCapController() {
            _context = new CHTTDbContext();
            _context.Configuration.ProxyCreationEnabled = false;
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public JsonResult LoadIndexData() {
            var model = _context.NhaCCs.ToList();
            return Json(new
            {
                data = model
            }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult AOEModal() {
            return View(new NhaCC());
        }

        [HttpGet]
        public JsonResult AddOrEdit(string strID, int par = 0) {
            string message = "";
            bool success = false;
            try
            {
                var model = _context.NhaCCs.Find(strID);
                message = "get data success";
                return Json(new
                {
                    data = model,
                    status = success,
                    message = message
                },JsonRequestBehavior.AllowGet);
            }
            catch (Exception e) {
                message = "getting is not successfully";
                return Json(new
                {

                    status = success,
                    message = message
                },JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public JsonResult AddOrEdit(string strData)
        {
            JavaScriptSerializer serializer = new JavaScriptSerializer();
            var model = serializer.Deserialize<NhaCC>(strData);
            bool success = false;
            string message = "";
            if (string.IsNullOrEmpty(model.MaNCC))
            {
                try
                {
                    NhaCC prevModel = _context.NhaCCs.OrderByDescending(x => x.MaNCC).FirstOrDefault();
                    int nextModelIDNum = int.Parse(prevModel.MaNCC.Substring(3));
                    nextModelIDNum += 1;
                    string nextModelID = "NCC" + nextModelIDNum;
                    if (nextModelID.Length != 5)
                    {
                        nextModelID = nextModelID.Insert(3, "0");
                    }
                    model.MaNCC = nextModelID;
                    _context.NhaCCs.Add(model);
                    _context.SaveChanges();
                    success = true;
                    message = "Thêm NCC \"" + model.TenNCC + "\" thành công";
                }
                catch (Exception e) {
                    success = false;
                    message = "Thêm NCC \"" + model.TenNCC + "\" thất bại";
                }
            }
            else {
                var editModel = _context.NhaCCs.Find(model.MaNCC);
                try
                {
                    editModel.TenNCC = model.TenNCC;
                    editModel.DiaChi = model.DiaChi;
                    editModel.SoDienThoai = model.SoDienThoai;
                    _context.SaveChanges();
                    success = true;
                    message = "Chỉnh sửa NCC \"" + editModel.TenNCC + "\" thành công";
                }
                catch (Exception e) {
                    success = false;
                    message = "Chỉnh sửa NCC \"" + editModel.TenNCC + "\" thất bại";
                }
            }
            return Json(new
            {
                status = success,
                message = message
            });
        }

        [HttpPost]
        public JsonResult Delete(string strID)
        {
            bool status = false;
            string message = "";
            var model = _context.NhaCCs.Find(strID);
            try
            {
                _context.NhaCCs.Remove(model);
                _context.SaveChanges();
                status = true;
                message = "Đã xóa nhà cung cấp \"" + model.TenNCC + "\"";
            }
            catch (Exception e) {
                message = "Lỗi! Chưa thể xóa nhà cung cấp \"" + model.TenNCC + "\"";
            }
            return Json(new
            {
                status = status,
                message = message
            });
        }
    }
}

CHTT/CHTT/Areas/Admin/Views/AdminNhaCungCap/AOEModal.cshtml
@model Model.Library.NhaCC


@{
    Layout = null;
}

<div id="aoe-modal" class="modal fade" role="dialog" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title"></h4>
                <button type="button" class="close" id="close-modal">&times;</button>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("AddOrEdit", "AdminNhaCungCap", FormMethod.Post, new { @id = "form-ncc" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(false)
                    @Html.HiddenFor(x => x.MaNCC, new { @id = "mancc-control" })
                    <div class="form-group">
                        @Html.LabelFor(x => x.TenNCC,"Tên nhà cung cấp:", new { @class = "label-control" })
                        @Html.TextBoxFor(x => x.TenNCC, new { @class = "form-control", @id = "tenncc-control" })
                        <span class="validation-message">Vui lòng không để trống - tối đa 200 ký tự.</span>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(x => x.DiaChi,"Địa chỉ:", new { @class = "label-control" })
                        @Html.TextBoxFor(x => x.DiaChi, new { @class = "form-control", @id = "diachi-control" })
                        <span class="validation-message">Vui lòng không để trống - tối đa 300 ký tự.</span>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(x => x.SoDienThoai,"Số điện thoại:", new { @class = "label-control" })
                        @Html.TextBoxFor(x => x.SoDienThoai, new { @class = "form-control", @id = "sdt-control" })
                        <span class="validation-message">Vui lòng không để trống.</span>
                    </div>
                }
            </div>
            <div class="modal-footer">
                <button class="btn btn-primary" id="save-button">Lưu</button>
                <button class="btn btn-dark" id="reset-button">Làm mới</button>
            </div>
        </div>

    </div>
</div>

CHTT/CHTT/Areas/Admin/Views/AdminNhaCungCap/Index.cshtml
@{
    ViewBag.Title = "Nhà cung cấp";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@*<link href="~/Areas/Admin/Contents/admin-page-style.css" rel="stylesheet" />*@
<link href="~/assets/admin/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
<link href="~/Areas/Admin/Contents/AdminNhaCungCapController.css" rel="stylesheet" />
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="font-weight-bold text-primary table-title">Danh sách nhà cung cấp</h6>
        <button class="btn btn-outline-primary btn-md" id="add-new-button" @*onclick="PopupForm('@Url.Action("AddOrEdit","AdminNhaCungCap")')"*@>
            <span>
                <i class="fa fa-plus" aria-hidden="true"></i>
                Thêm
            </span>
        </button>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered table-striped" id="NCCTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <td>Mã số</td>
                        <td>Tên gọi</td>
                        <td>Địa chỉ</td>
                        <td>Số điện thoại</td>
                        <td>Hành động</td>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>
<div id="aoe-container">
    @Html.Partial("AOEModal")
</div>
<script src="~/assets/admin/vendor/datatables/jquery.dataTables.min.js"></script>
<script src="~/assets/admin/vendor/datatables/dataTables.bootstrap4.min.js"></script>
<script src="~/assets/admin/vendor/notify/notify.min.js"></script>
<script src="~/Areas/Admin/Scripts/controllers/AdminNhaCungCapController.js"></script>

CHTT/CHTT/Areas/Admin/Views/AdminNhaCungCap/getModalView.cshtml
@model Model.NhaCC

@{
    Layout = null;
}

<div id="aoe-modal" class="modal fade" role="dialog" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title"></h4>
                <button type="button" class="close" id="close-modal">&times;</button>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("AddOrEdit", "AdminNhaCungCap", FormMethod.Post, new { @id = "form-ncc" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(false)
                    @Html.HiddenFor(x => x.MaNCC, new { @id="mancc-control"})
                    <div class="form-group">
                        @Html.LabelFor(x => x.TenNCC, new { @class = "label-control" })
                        @Html.TextBoxFor(x => x.TenNCC, new { @class = "form-control" ,@id="tenncc-control"})
                        <span class="validation-message">Vui lòng không để trống, tối đa 200 ký tự.</span>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(x => x.DiaChi, new { @class = "label-control" })
                        @Html.TextBoxFor(x => x.DiaChi, new { @class = "form-control", @id = "diachi-control" })
                        <span class="validation-message">Vui lòng không để trống, tối đa 300 ký tự.</span>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(x => x.SoDienThoai, new { @class = "label-control" })
                        @Html.TextBoxFor(x => x.SoDienThoai, new { @class = "form-control", @id = "sdt-control" })
                        <span class="validation-message">Vui lòng không để trống và nhập đúng định dạng.</span>
                    </div>
                }
            </div>
            <div class="modal-footer">
                <button class="btn btn-primary" id="save-button">Lưu</button>
                <button class="btn btn-dark" id="reset-button">Làm mới</button>
            </div>
        </div>

    </div>
</div>